# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarme',
            fields=[
                ('uid', models.CharField(blank=True, max_length=48, null=True)),
                ('codigoAlarme', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('mensagemAlarme', models.CharField(max_length=255)),
                ('prioridadeAlarme', models.IntegerField()),
                ('ativo', models.BooleanField(default=False)),
                ('tempoAtivacao', models.DateTimeField()),
                ('syncAtivacao', models.BooleanField(default=False)),
                ('tempoInativacao', models.DateTimeField(null=True)),
                ('syncInativacao', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Alarme',
                'verbose_name_plural': 'Alarmes',
            },
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
            },
        ),
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxAlarmes', models.IntegerField()),
                ('portaSerial', models.CharField(default='/dev/ttyAMA0', max_length=20)),
                ('taxa', models.IntegerField(default=115200)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=6)),
                ('mensagem', models.CharField(max_length=255)),
                ('sync', models.BooleanField(default=False)),
                ('tempo', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.AddField(
            model_name='alarme',
            name='ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacao.Ambiente'),
        ),
    ]
