# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarme',
            name='ambiente',
        ),
        migrations.DeleteModel(
            name='Alarme',
        ),
    ]
