# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mqtt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'Não configurado'), (1, 'Funcionando'), (2, 'Falha na comunicação'), (3, 'Erro')], default=0, verbose_name='Estado da comunicação')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('servidor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço do servidor')),
            ],
            options={
                'verbose_name': 'Configurações da comunicação MQTT',
            },
        ),
    ]
