# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=48, null=True)),
                ('codigoAlarme', models.CharField(max_length=36)),
                ('mensagemAlarme', models.CharField(max_length=255)),
                ('prioridadeAlarme', models.IntegerField()),
                ('ativo', models.BooleanField(default=False)),
                ('tempoAtivacao', models.DateTimeField()),
                ('syncAtivacao', models.BooleanField(default=False)),
                ('tempoInativacao', models.DateTimeField(null=True)),
                ('syncInativacao', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Alarme',
                'verbose_name_plural': 'Alarmes',
            },
        ),
        migrations.CreateModel(
            name='AlarmeAnalogico',
            fields=[
                ('codigoAlarme', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('mensagemAlarme', models.CharField(max_length=255, verbose_name='Mensagem do alarme')),
                ('prioridadeAlarme', models.IntegerField(verbose_name='Prioridade do alarme')),
                ('valorAlarmeOn', models.FloatField(verbose_name='Valor para ativar o alarme')),
                ('valorAlarmeOff', models.FloatField(verbose_name='Valor para desativar o alarme')),
            ],
            options={
                'verbose_name': 'Alarme Analógico',
                'verbose_name_plural': 'Alarmes Analógicos',
            },
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('uid', models.CharField(blank=True, max_length=48, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
            },
        ),
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiKey', models.CharField(max_length=255, unique=True)),
                ('authDomain', models.CharField(max_length=255, unique=True)),
                ('databaseURL', models.CharField(max_length=255, unique=True)),
                ('storageBucket', models.CharField(max_length=255, unique=True)),
                ('uidCentral', models.CharField(max_length=48, unique=True)),
                ('maxAlarmes', models.IntegerField()),
                ('portaSerial', models.CharField(default='/dev/ttyAMA0', max_length=20)),
                ('taxa', models.IntegerField(default=115200)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.CreateModel(
            name='EntradaDigital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=False)),
                ('triggerAlarme', models.BooleanField(default=False, verbose_name='Estado para alarme')),
                ('codigoAlarme', models.CharField(default=None, max_length=36)),
                ('mensagemAlarme', models.CharField(max_length=255, verbose_name='Mensagem do alarme')),
                ('prioridadeAlarme', models.IntegerField(verbose_name='Prioridade do alarme')),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('sync', models.BooleanField(default=False)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.Ambiente')),
            ],
            options={
                'verbose_name': 'Entrada digital',
                'verbose_name_plural': 'Entradas digitais',
            },
        ),
        migrations.CreateModel(
            name='Grandeza',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('unidade', models.CharField(max_length=15, unique=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('sync', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Grandeza',
                'verbose_name_plural': 'Grandezas',
            },
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('sync', models.BooleanField(default=False)),
                ('ambiente', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='central.Ambiente')),
                ('grandeza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.Grandeza')),
            ],
            options={
                'verbose_name': 'Leitura',
                'verbose_name_plural': 'Leituras',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=6)),
                ('mensagem', models.CharField(max_length=255)),
                ('sync', models.BooleanField(default=False)),
                ('tempo', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='PlacaExpansaoDigital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRede', models.IntegerField(unique=True)),
                ('descricao', models.CharField(max_length=255, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Placa de expansão digital',
                'verbose_name_plural': 'Placas de expansão digital',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRede', models.IntegerField(unique=True)),
                ('uid', models.CharField(blank=True, max_length=48, null=True)),
                ('descricao', models.CharField(default='', max_length=255, unique=True)),
                ('intervaloAtualizacao', models.IntegerField(default=2)),
                ('intervaloLeitura', models.IntegerField(default=2)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('sync', models.BooleanField(default=False)),
                ('ambiente', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='central.Ambiente')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
            },
        ),
        migrations.CreateModel(
            name='SensorGrandeza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('curvaCalibracao', models.CharField(max_length=255)),
                ('sync', models.BooleanField(default=False)),
                ('grandeza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.Grandeza')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.Sensor', to_field='idRede')),
            ],
            options={
                'verbose_name': 'Grandeza do Sensor',
                'verbose_name_plural': 'Grandezas dos Sensores',
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='grandezas',
            field=models.ManyToManyField(through='central.SensorGrandeza', to='central.Grandeza'),
        ),
        migrations.AddField(
            model_name='leitura',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.Sensor', to_field='idRede'),
        ),
        migrations.AddField(
            model_name='entradadigital',
            name='placaExpansaoDigital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.PlacaExpansaoDigital', to_field='idRede', verbose_name='Placa de expansão digital'),
        ),
        migrations.AddField(
            model_name='alarmeanalogico',
            name='ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.Ambiente'),
        ),
        migrations.AddField(
            model_name='alarmeanalogico',
            name='grandeza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.Grandeza'),
        ),
        migrations.AddField(
            model_name='alarme',
            name='ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.Ambiente'),
        ),
        migrations.AlterUniqueTogether(
            name='sensorgrandeza',
            unique_together=set([('grandeza', 'sensor')]),
        ),
        migrations.AlterUniqueTogether(
            name='entradadigital',
            unique_together=set([('placaExpansaoDigital', 'numero')]),
        ),
    ]
