# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=48, null=True)),
                ('ativo', models.BooleanField(default=False)),
                ('tempoAtivacao', models.DateTimeField()),
                ('syncAtivacao', models.BooleanField(default=False)),
                ('tempoInativacao', models.DateTimeField(null=True)),
                ('syncInativacao', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Alarmes',
                'verbose_name': 'Alarme',
            },
        ),
        migrations.CreateModel(
            name='AlarmeTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('mensagem', models.CharField(max_length=255, unique=True)),
                ('prioridade', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Tipos de Alarme',
                'verbose_name': 'Tipo de Alarme',
            },
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('uid', models.CharField(blank=True, max_length=48, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ambientes',
                'verbose_name': 'Ambiente',
            },
        ),
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiKey', models.CharField(max_length=255)),
                ('authDomain', models.CharField(max_length=255)),
                ('databaseURL', models.CharField(max_length=255)),
                ('storageBucket', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('uidCentral', models.CharField(max_length=48)),
                ('maxAlarmes', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Configuração',
                'verbose_name': 'Configuração',
            },
        ),
        migrations.CreateModel(
            name='EntradaDigital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync', models.BooleanField(default=False)),
                ('alarmeTipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='central.AlarmeTipo', to_field='codigo')),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.Ambiente')),
            ],
            options={
                'verbose_name_plural': 'Entradas digitais',
                'verbose_name': 'Entrada digital',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=6)),
                ('mensagem', models.CharField(max_length=255)),
                ('sync', models.BooleanField(default=False)),
                ('tempo', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Logs',
                'verbose_name': 'Log',
            },
        ),
        migrations.CreateModel(
            name='PlacaExpansaoDigital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRede', models.IntegerField(unique=True)),
                ('descricao', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Placas de expansão digital',
                'verbose_name': 'Placa de expansão digital',
            },
        ),
        migrations.AddField(
            model_name='entradadigital',
            name='placaExpansaoDigital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.PlacaExpansaoDigital', to_field='idRede'),
        ),
        migrations.AddField(
            model_name='alarme',
            name='alarmeTipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.AlarmeTipo'),
        ),
        migrations.AddField(
            model_name='alarme',
            name='ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.Ambiente'),
        ),
    ]
