# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False)),
                ('tempoAtivacao', models.DateTimeField()),
                ('syncAtivacao', models.BooleanField(default=False)),
                ('tempoInativacao', models.DateTimeField(null=True)),
                ('syncInativacao', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AlarmeTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('mensagem', models.CharField(max_length=255, unique=True)),
                ('prioridade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EntradaDigital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync', models.BooleanField(default=False)),
                ('codigoAlarme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central.AlarmeTipo')),
            ],
        ),
        migrations.CreateModel(
            name='PlacaExpansaoDigital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRede', models.IntegerField(unique=True)),
                ('descricao', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='entradadigital',
            name='codigoPlacaExpansaoDigital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central.PlacaExpansaoDigital'),
        ),
        migrations.AddField(
            model_name='alarme',
            name='codigoAlarme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central.AlarmeTipo'),
        ),
    ]
