# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('sync', models.BooleanField(default=False)),
                ('ambiente', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='central.Ambiente')),
                ('grandeza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.Grandeza', to_field='codigo')),
            ],
            options={
                'verbose_name_plural': 'Leituras',
                'verbose_name': 'Leitura',
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='ambiente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='central.Ambiente'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensorgrandeza',
            name='sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leitura',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.Sensor', to_field='idRede'),
        ),
    ]
