# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2017-03-28 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidaDigital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('ativa', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=False)),
                ('tempoLigado', models.IntegerField(verbose_name='Tempo ligado em segundos')),
                ('tempoDesligado', models.IntegerField(verbose_name='Tempo desligado em segundos')),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('ultimoAcionamento', models.DateTimeField(null=True)),
                ('sync', models.BooleanField(default=False)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.Ambiente')),
                ('placaExpansaoDigital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.PlacaExpansaoDigital', to_field='idRede', verbose_name='Placa de expansão digital')),
            ],
            options={
                'verbose_name': 'Saida digital',
                'verbose_name_plural': 'Saidas digitais',
            },
        ),
        migrations.RemoveField(
            model_name='configuracoes',
            name='apiKey',
        ),
        migrations.RemoveField(
            model_name='configuracoes',
            name='authDomain',
        ),
        migrations.RemoveField(
            model_name='configuracoes',
            name='databaseURL',
        ),
        migrations.RemoveField(
            model_name='configuracoes',
            name='storageBucket',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='createdAt',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='saidadigital',
            unique_together=set([('placaExpansaoDigital', 'numero')]),
        ),
    ]
