# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracoes',
            name='apiKey',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='configuracoes',
            name='authDomain',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='configuracoes',
            name='databaseURL',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='configuracoes',
            name='storageBucket',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='configuracoes',
            name='uidCentral',
            field=models.CharField(max_length=48, unique=True),
        ),
    ]
