# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0002_auto_20170209_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grandeza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('unidade', models.CharField(max_length=15, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Grandeza',
                'verbose_name_plural': 'Grandezas',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRede', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=255, null=True)),
                ('intervaloAtualizacao', models.IntegerField(default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
            },
        ),
        migrations.CreateModel(
            name='SensorGrandeza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curvaCalibracao', models.CharField(max_length=255)),
                ('grandeza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.Grandeza', to_field='codigo')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.Sensor', to_field='idRede')),
            ],
            options={
                'verbose_name': 'Grandeza do Sensor',
                'verbose_name_plural': 'Grandezas dos Sensores',
            },
        ),
    ]
