# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0002_auto_20170127_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradadigital',
            name='codigoAlarme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='central.AlarmeTipo'),
        ),
    ]
