# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0003_auto_20170210_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='descricao',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
