# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0003_auto_20170127_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entradadigital',
            old_name='codigoPlacaExpansaoDigital',
            new_name='placaExpansaoDigital',
        ),
        migrations.AlterUniqueTogether(
            name='entradadigital',
            unique_together=set([('placaExpansaoDigital', 'numero')]),
        ),
    ]
