# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0003_grandeza_sensor_sensorgrandeza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorgrandeza',
            name='obs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
