# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0004_auto_20170127_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarme',
            old_name='codigoAlarme',
            new_name='alarmeTipo',
        ),
        migrations.RenameField(
            model_name='entradadigital',
            old_name='codigoAlarme',
            new_name='alarmeTipo',
        ),
    ]
