# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0004_auto_20170210_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorgrandeza',
            name='updated_at',
        ),
    ]
