# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0005_remove_sensorgrandeza_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorgrandeza',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
