# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0005_auto_20170128_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarme',
            name='alarmeTipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.AlarmeTipo'),
        ),
        migrations.AlterField(
            model_name='entradadigital',
            name='alarmeTipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='central.AlarmeTipo', to_field='codigo'),
        ),
        migrations.AlterField(
            model_name='entradadigital',
            name='placaExpansaoDigital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.PlacaExpansaoDigital', to_field='idRede'),
        ),
    ]
