# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0006_sensorgrandeza_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='grandezas',
            field=models.ManyToManyField(to='central.Grandeza'),
        ),
    ]
