# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0007_sensor_grandezas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SensorGrandeza',
            new_name='Sensor_grandeza',
        ),
    ]
