# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0008_auto_20170210_1553'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensor_grandeza',
            new_name='SensorGrandeza',
        ),
    ]
